mongo_connection_string: mongodb://root:password@localhost:27017/
mongo_database: capgo
s3_base_endpoint: http://localhost:9000
s3_bucket: "test"
management_api_tokens:
- key1
- key2
cache_result_duration: 1s
