version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - mongo
            - minio
        environment:
            - MONGO_CONNECTION_STRING=mongodb://root:password@mongo:27017
            - AWS_ACCESS_KEY_ID=minioadmin
            - AWS_SECRET_ACCESS_KEY=minioadmin
            - AWS_REGION=ap-southeast-1
            - S3_BASE_ENDPOINT=http://minio:9000
        volumes:
            - ./config.yml:/app/config.yml

    mongo:
        image: mongo:5
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        environment:
            - MONGO_INITDB_DATABASE=capgo
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password

    minio:
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
            - MINIO_DEFAULT_BUCKETS=test
        command: server /data --console-address ":9001"

volumes:
    mongo_data:
    minio_data:
